name: finney
description: "A financial app that helps you manage your money and make informed decisions about your finances."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: 5.6.5
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  flutter_gemini: ^3.0.0
  image_picker: ^1.0.7
  dash_chat_2: ^0.0.20
  google_nav_bar: ^5.0.7
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  hive_ui: ^1.0.14
  fl_chart: ^0.65.0
  intl: ^0.19.0
  flutter_tts: ^4.2.2
  flutter_slidable: ^3.0.1
  url_launcher: ^6.2.5
  speech_to_text: ^7.0.0
  lottie: ^3.0.0
  flutter_localization: ^0.3.2
  sprintf: ^7.0.0
  lucide_icons: ^0.257.0
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.0.0-beta.24
  translator: 0.1.7
  google_fonts: 4.0.4
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  flutter_secure_storage: ^9.2.2
  uuid: ^3.0.7
  local_auth: ^2.3.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  android_intent_plus: ^3.1.9

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - lib/shared/images/
    - lib/shared/animations/
  fonts:
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-VariableFont_wdth,wght.ttf

flutter_launcher_icons:
  android: true
  image_path: 'lib/shared/images/logo_launch.png'