import 'package:hive/hive.dart';

part 'user_model.g.dart';  // This file is generated by the build_runner tool

@HiveType(typeId: 0)  // The typeId should be unique for each model
class UserModel {
  @HiveField(0)
  final String uid;

  @HiveField(1)
  final String email;

  @HiveField(2)
  final String name;

  UserModel({required this.uid, required this.email, required this.name});
}
